version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "minidiscord"
s3_bucket = "minidiscord"
s3_prefix = "minidiscord"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"