AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

  Sample SAM Template for backend

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: discord-back-end
      CodeUri: lambdas/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - Version: "2012-10-17"
        Statement: 
        - Effect: "Allow"
          Action:
            - "cognito-idp:*"
            - "dynamodb:*"
            - "apigateway:*"
          Resource: '*'

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
